export const users = [
  {
    userId: 1,
    firstName: "Jan",
    lastName: "Kowalski",
    phoneNumber: "607934182",
    email: "jan_k@email.com",
    role: "administrator",
    status: "aktywny",
  },
  {
    userId: 4,
    firstName: "Agata",
    lastName: "Krzeszowska",
    phoneNumber: "685234054",
    email: "agata_k@email.com",
    role: "technolog",
    status: "aktywny",
  },
  {
    userId: 3,
    firstName: "Andrzej",
    lastName: "Malinowski",
    phoneNumber: "679234374",
    email: "andrzej_m@email.com",
    role: "kierownik produkcji",
    status: "aktywny",
  },
  {
    userId: 2,
    firstName: "Anna",
    lastName: "Nowak",
    phoneNumber: "709856234",
    email: "anna_n@email.com",
    role: "handlowiec",
    status: "aktywny",
  },
  {
    userId: 5,
    firstName: "Edward",
    lastName: "Rak",
    phoneNumber: "978345278",
    email: "edward_r@email.com",
    role: "magazynier",
    status: "aktywny",
  },
];
